apiVersion: apps/v1
kind: Deployment
metadata:
  name: resumelo
  namespace: resumelo
spec:
  template:
    spec:
      containers:
        - name: resumelo
          image: "registry.yesidlopez.de/resumelo:0.8.0" # {"$imagepolicy": "resumelo:resumelo-prod"} 
